name: simple_deploymnet_pipline

on:
  push:
    branches:
    - main

jobs:
  deployment:
    name: deployment_job
    runs-on: ubuntu-latest

    steps:
      - name: checking-out code
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
      - name: installing dependencies
        run: npm install
      - name: build code
        run: npm run build
      - name: running tests
        run: npm test
